// AUTOGENERATED Components module
pub mod badge;
pub mod button;
pub mod card;
pub mod input;

// PR2 adopting 组件（feat/ui-shadcn-gap）
pub mod avatar;
pub mod dropdown_menu;
pub mod select;
pub mod sheet;
pub mod sidebar;
pub mod skeleton;
pub mod switch;
pub mod toast;

// 展示卡牌组件（feat/overview-card-styles #193）
pub mod showcase;

// 排行榜条目卡（feat/overview-ui #204）
pub mod rank_board;

// 管理台统计卡（收敛 groups/users/keys/usage_logs 四处重复定义）
pub mod stat_card;

// 管理面板专用卡牌组件（feat/admin-card-kit）
pub mod admin_card;

// 布局原语（feat/layout）
pub mod layout;
// 新迁组件族（feat/ui-components-structure）
pub mod action_buttons;
pub mod auth;
pub mod bubble;
pub mod decision;
pub mod feedback;
pub mod form;
pub mod icons;
pub mod nav;
pub mod overlay;
pub mod panel;
pub mod segmented;
