[package]
name = "tavern-secrets"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tavern-storage = { path = "../tavern-storage" }

serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }
axum       = { workspace = true }
