[package]
name = "page-admin"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
dioxus    = { workspace = true }
ui       = { path = "../ui" }
gloo-timers = { version = "0.3", features = ["futures"] }
web-sys = { version = "0.3", features = ["Window", "Performance"] }
client = { path = "../client" }
contract = { path = "../../contract" }
serde = { workspace = true }
serde_json = { workspace = true }
