[package]
name = "ui-components"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
contract   = { path = "../../contract" }
dioxus     = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
gloo-net   = { workspace = true }
dioxus-icons = { version = "0.1.0", default-features = false }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys    = { version = "0.3", features = ["Window", "Storage", "Navigator", "Clipboard"] }
