[package]
name = "tavern-page-characters"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tavern-client = { path = "../tavern-client" }
tavern-state  = { path = "../tavern-state" }
tavern-ui     = { package = "ui-components", path = "../ui-components" }

dioxus = { workspace = true }
tavern-page-personas = { path = "../tavern-page-personas" }
tavern-page-lorebook = { path = "../tavern-page-lorebook" }
