[package]
name = "tavern-page-chat"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tavern-client = { path = "../tavern-client" }
tavern-state  = { path = "../tavern-state" }
tavern-ui     = { path = "../tavern-ui" }

dioxus = { workspace = true }
