[package]
name = "page-users"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
dioxus = { workspace = true }
ui = { path = "../admin-ui" }
mock = { path = "../admin-mock" }
chrono = { workspace = true }
client = { path = "../admin-client" }
contract = { path = "../../contract" }
serde = { workspace = true }
serde_json = { workspace = true }
