[package]
name = "api"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "api"
path = "src/lib.rs"

[[bin]]
name = "ferrite"
path = "src/main.rs"

[dependencies]
axum      = { workspace = true }
tokio     = { workspace = true }
reqwest   = { workspace = true }
serde     = { workspace = true }
serde_json = { workspace = true }
toml      = { workspace = true }
sqlx      = { workspace = true }
tracing   = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
bytes     = { workspace = true }
tracing-log = { workspace = true }
tracing-appender = { workspace = true }
tower-http = { workspace = true }
arc-swap  = { workspace = true }
rand      = { workspace = true }
chrono    = { workspace = true }
futures-util = { workspace = true }
tower     = { workspace = true }

tavern-storage    = { path = "../../crates/api/tavern-storage" }
tavern-auth       = { path = "../../crates/api/tavern-auth" }
tavern-characters = { path = "../../crates/api/tavern-characters" }
tavern-chats      = { path = "../../crates/api/tavern-chats" }
tavern-settings   = { path = "../../crates/api/tavern-settings" }
tavern-secrets    = { path = "../../crates/api/tavern-secrets" }
tavern-generate   = { path = "../../crates/api/tavern-generate" }
auth              = { path = "../../crates/api/auth" }
